services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db_events
    ports:
      - '3306:3306'
    networks:
      - nlw-network
networks:
  nlw-network:
    driver: bridge
